package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"../../server/restapi/operations/key_service"
)

// NewKeyProtoAPI creates a new KeyProto instance
func NewKeyProtoAPI(spec *loads.Document) *KeyProtoAPI {
	return &KeyProtoAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
		ServeError:      errors.ServeError,
		JSONConsumer:    runtime.JSONConsumer(),
		JSONProducer:    runtime.JSONProducer(),
		KeyServiceKeyServiceAddKeyHandler: key_service.KeyServiceAddKeyHandlerFunc(func(params key_service.KeyServiceAddKeyParams) middleware.Responder {
			return middleware.NotImplemented("operation KeyServiceKeyServiceAddKey has not yet been implemented")
		}),
		KeyServiceKeyServiceDeleteKeyHandler: key_service.KeyServiceDeleteKeyHandlerFunc(func(params key_service.KeyServiceDeleteKeyParams) middleware.Responder {
			return middleware.NotImplemented("operation KeyServiceKeyServiceDeleteKey has not yet been implemented")
		}),
		KeyServiceKeyServiceGetKeyHandler: key_service.KeyServiceGetKeyHandlerFunc(func(params key_service.KeyServiceGetKeyParams) middleware.Responder {
			return middleware.NotImplemented("operation KeyServiceKeyServiceGetKey has not yet been implemented")
		}),
		KeyServiceKeyServiceGetPageHandler: key_service.KeyServiceGetPageHandlerFunc(func(params key_service.KeyServiceGetPageParams) middleware.Responder {
			return middleware.NotImplemented("operation KeyServiceKeyServiceGetPage has not yet been implemented")
		}),
		KeyServiceKeyServiceGetPageContinuedHandler: key_service.KeyServiceGetPageContinuedHandlerFunc(func(params key_service.KeyServiceGetPageContinuedParams) middleware.Responder {
			return middleware.NotImplemented("operation KeyServiceKeyServiceGetPageContinued has not yet been implemented")
		}),
	}
}

/*KeyProtoAPI the key proto API */
type KeyProtoAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// KeyServiceKeyServiceAddKeyHandler sets the operation handler for the key service add key operation
	KeyServiceKeyServiceAddKeyHandler key_service.KeyServiceAddKeyHandler
	// KeyServiceKeyServiceDeleteKeyHandler sets the operation handler for the key service delete key operation
	KeyServiceKeyServiceDeleteKeyHandler key_service.KeyServiceDeleteKeyHandler
	// KeyServiceKeyServiceGetKeyHandler sets the operation handler for the key service get key operation
	KeyServiceKeyServiceGetKeyHandler key_service.KeyServiceGetKeyHandler
	// KeyServiceKeyServiceGetPageHandler sets the operation handler for the key service get page operation
	KeyServiceKeyServiceGetPageHandler key_service.KeyServiceGetPageHandler
	// KeyServiceKeyServiceGetPageContinuedHandler sets the operation handler for the key service get page continued operation
	KeyServiceKeyServiceGetPageContinuedHandler key_service.KeyServiceGetPageContinuedHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *KeyProtoAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *KeyProtoAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *KeyProtoAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *KeyProtoAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *KeyProtoAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *KeyProtoAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *KeyProtoAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the KeyProtoAPI
func (o *KeyProtoAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.KeyServiceKeyServiceAddKeyHandler == nil {
		unregistered = append(unregistered, "key_service.KeyServiceAddKeyHandler")
	}

	if o.KeyServiceKeyServiceDeleteKeyHandler == nil {
		unregistered = append(unregistered, "key_service.KeyServiceDeleteKeyHandler")
	}

	if o.KeyServiceKeyServiceGetKeyHandler == nil {
		unregistered = append(unregistered, "key_service.KeyServiceGetKeyHandler")
	}

	if o.KeyServiceKeyServiceGetPageHandler == nil {
		unregistered = append(unregistered, "key_service.KeyServiceGetPageHandler")
	}

	if o.KeyServiceKeyServiceGetPageContinuedHandler == nil {
		unregistered = append(unregistered, "key_service.KeyServiceGetPageContinuedHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *KeyProtoAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *KeyProtoAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *KeyProtoAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *KeyProtoAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *KeyProtoAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the key proto API
func (o *KeyProtoAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *KeyProtoAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/keys"] = key_service.NewKeyServiceAddKey(o.context, o.KeyServiceKeyServiceAddKeyHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/keys/{id}"] = key_service.NewKeyServiceDeleteKey(o.context, o.KeyServiceKeyServiceDeleteKeyHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/keys/{id}"] = key_service.NewKeyServiceGetKey(o.context, o.KeyServiceKeyServiceGetKeyHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/keys"] = key_service.NewKeyServiceGetPage(o.context, o.KeyServiceKeyServiceGetPageHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/keys-continued-list"] = key_service.NewKeyServiceGetPageContinued(o.context, o.KeyServiceKeyServiceGetPageContinuedHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *KeyProtoAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *KeyProtoAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
