package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../server/models"
)

// KeyServiceGetPageContinuedOKCode is the HTTP code returned for type KeyServiceGetPageContinuedOK
const KeyServiceGetPageContinuedOKCode int = 200

/*KeyServiceGetPageContinuedOK A successful response.

swagger:response keyServiceGetPageContinuedOK
*/
type KeyServiceGetPageContinuedOK struct {

	/*
	  In: Body
	*/
	Payload *models.ExampleListKeysResponse `json:"body,omitempty"`
}

// NewKeyServiceGetPageContinuedOK creates KeyServiceGetPageContinuedOK with default headers values
func NewKeyServiceGetPageContinuedOK() *KeyServiceGetPageContinuedOK {
	return &KeyServiceGetPageContinuedOK{}
}

// WithPayload adds the payload to the key service get page continued o k response
func (o *KeyServiceGetPageContinuedOK) WithPayload(payload *models.ExampleListKeysResponse) *KeyServiceGetPageContinuedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the key service get page continued o k response
func (o *KeyServiceGetPageContinuedOK) SetPayload(payload *models.ExampleListKeysResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KeyServiceGetPageContinuedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*KeyServiceGetPageContinuedDefault An unexpected error response.

swagger:response keyServiceGetPageContinuedDefault
*/
type KeyServiceGetPageContinuedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RuntimeError `json:"body,omitempty"`
}

// NewKeyServiceGetPageContinuedDefault creates KeyServiceGetPageContinuedDefault with default headers values
func NewKeyServiceGetPageContinuedDefault(code int) *KeyServiceGetPageContinuedDefault {
	if code <= 0 {
		code = 500
	}

	return &KeyServiceGetPageContinuedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the key service get page continued default response
func (o *KeyServiceGetPageContinuedDefault) WithStatusCode(code int) *KeyServiceGetPageContinuedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the key service get page continued default response
func (o *KeyServiceGetPageContinuedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the key service get page continued default response
func (o *KeyServiceGetPageContinuedDefault) WithPayload(payload *models.RuntimeError) *KeyServiceGetPageContinuedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the key service get page continued default response
func (o *KeyServiceGetPageContinuedDefault) SetPayload(payload *models.RuntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KeyServiceGetPageContinuedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
