package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyServiceGetPageContinuedParams creates a new KeyServiceGetPageContinuedParams object
// with the default values initialized.
func NewKeyServiceGetPageContinuedParams() KeyServiceGetPageContinuedParams {
	var ()
	return KeyServiceGetPageContinuedParams{}
}

// KeyServiceGetPageContinuedParams contains all the bound params for the key service get page continued operation
// typically these are obtained from a http.Request
//
// swagger:parameters KeyService_GetPageContinued
type KeyServiceGetPageContinuedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: query
	*/
	PageSize *int32
	/*
	  In: query
	*/
	PageToken *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *KeyServiceGetPageContinuedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPageSize, qhkPageSize, _ := qs.GetOK("page_size")
	if err := o.bindPageSize(qPageSize, qhkPageSize, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageToken, qhkPageToken, _ := qs.GetOK("page_token")
	if err := o.bindPageToken(qPageToken, qhkPageToken, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KeyServiceGetPageContinuedParams) bindPageSize(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("page_size", "query", "int32", raw)
	}
	o.PageSize = &value

	return nil
}

func (o *KeyServiceGetPageContinuedParams) bindPageToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.PageToken = &raw

	return nil
}
