package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExampleAddingKeyStatus Represents the status of key adding
// swagger:model exampleAddingKeyStatus
type ExampleAddingKeyStatus struct {

	// id
	ID int32 `json:"id,omitempty"`

	// status
	Status bool `json:"status,omitempty"`
}

// Validate validates this example adding key status
func (m *ExampleAddingKeyStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
