package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ProtobufAny protobuf any
// swagger:model protobufAny
type ProtobufAny struct {

	// type url
	TypeURL string `json:"type_url,omitempty"`

	// value
	Value strfmt.Base64 `json:"value,omitempty"`
}

// Validate validates this protobuf any
func (m *ProtobufAny) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
