package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyServiceGetPageParams creates a new KeyServiceGetPageParams object
// with the default values initialized.
func NewKeyServiceGetPageParams() *KeyServiceGetPageParams {
	var ()
	return &KeyServiceGetPageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyServiceGetPageParamsWithTimeout creates a new KeyServiceGetPageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyServiceGetPageParamsWithTimeout(timeout time.Duration) *KeyServiceGetPageParams {
	var ()
	return &KeyServiceGetPageParams{

		timeout: timeout,
	}
}

// NewKeyServiceGetPageParamsWithContext creates a new KeyServiceGetPageParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyServiceGetPageParamsWithContext(ctx context.Context) *KeyServiceGetPageParams {
	var ()
	return &KeyServiceGetPageParams{

		Context: ctx,
	}
}

// NewKeyServiceGetPageParamsWithHTTPClient creates a new KeyServiceGetPageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyServiceGetPageParamsWithHTTPClient(client *http.Client) *KeyServiceGetPageParams {
	var ()
	return &KeyServiceGetPageParams{
		HTTPClient: client,
	}
}

/*KeyServiceGetPageParams contains all the parameters to send to the API endpoint
for the key service get page operation typically these are written to a http.Request
*/
type KeyServiceGetPageParams struct {

	/*PageNumber*/
	PageNumber *int32
	/*PageSize*/
	PageSize *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key service get page params
func (o *KeyServiceGetPageParams) WithTimeout(timeout time.Duration) *KeyServiceGetPageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key service get page params
func (o *KeyServiceGetPageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key service get page params
func (o *KeyServiceGetPageParams) WithContext(ctx context.Context) *KeyServiceGetPageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key service get page params
func (o *KeyServiceGetPageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key service get page params
func (o *KeyServiceGetPageParams) WithHTTPClient(client *http.Client) *KeyServiceGetPageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key service get page params
func (o *KeyServiceGetPageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageNumber adds the pageNumber to the key service get page params
func (o *KeyServiceGetPageParams) WithPageNumber(pageNumber *int32) *KeyServiceGetPageParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the key service get page params
func (o *KeyServiceGetPageParams) SetPageNumber(pageNumber *int32) {
	o.PageNumber = pageNumber
}

// WithPageSize adds the pageSize to the key service get page params
func (o *KeyServiceGetPageParams) WithPageSize(pageSize *int32) *KeyServiceGetPageParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the key service get page params
func (o *KeyServiceGetPageParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *KeyServiceGetPageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageNumber != nil {

		// query param page_number
		var qrPageNumber int32
		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt32(qrPageNumber)
		if qPageNumber != "" {
			if err := r.SetQueryParam("page_number", qPageNumber); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
