package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyServiceGetPageContinuedParams creates a new KeyServiceGetPageContinuedParams object
// with the default values initialized.
func NewKeyServiceGetPageContinuedParams() *KeyServiceGetPageContinuedParams {
	var ()
	return &KeyServiceGetPageContinuedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyServiceGetPageContinuedParamsWithTimeout creates a new KeyServiceGetPageContinuedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyServiceGetPageContinuedParamsWithTimeout(timeout time.Duration) *KeyServiceGetPageContinuedParams {
	var ()
	return &KeyServiceGetPageContinuedParams{

		timeout: timeout,
	}
}

// NewKeyServiceGetPageContinuedParamsWithContext creates a new KeyServiceGetPageContinuedParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyServiceGetPageContinuedParamsWithContext(ctx context.Context) *KeyServiceGetPageContinuedParams {
	var ()
	return &KeyServiceGetPageContinuedParams{

		Context: ctx,
	}
}

// NewKeyServiceGetPageContinuedParamsWithHTTPClient creates a new KeyServiceGetPageContinuedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyServiceGetPageContinuedParamsWithHTTPClient(client *http.Client) *KeyServiceGetPageContinuedParams {
	var ()
	return &KeyServiceGetPageContinuedParams{
		HTTPClient: client,
	}
}

/*KeyServiceGetPageContinuedParams contains all the parameters to send to the API endpoint
for the key service get page continued operation typically these are written to a http.Request
*/
type KeyServiceGetPageContinuedParams struct {

	/*PageSize*/
	PageSize *int32
	/*PageToken*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) WithTimeout(timeout time.Duration) *KeyServiceGetPageContinuedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) WithContext(ctx context.Context) *KeyServiceGetPageContinuedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) WithHTTPClient(client *http.Client) *KeyServiceGetPageContinuedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageSize adds the pageSize to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) WithPageSize(pageSize *int32) *KeyServiceGetPageContinuedParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) WithPageToken(pageToken *string) *KeyServiceGetPageContinuedParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the key service get page continued params
func (o *KeyServiceGetPageContinuedParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *KeyServiceGetPageContinuedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string
		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {
			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
