package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"../../client/models"
)

// KeyServiceAddKeyReader is a Reader for the KeyServiceAddKey structure.
type KeyServiceAddKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KeyServiceAddKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewKeyServiceAddKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewKeyServiceAddKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKeyServiceAddKeyOK creates a KeyServiceAddKeyOK with default headers values
func NewKeyServiceAddKeyOK() *KeyServiceAddKeyOK {
	return &KeyServiceAddKeyOK{}
}

/*KeyServiceAddKeyOK handles this case with default header values.

A successful response.
*/
type KeyServiceAddKeyOK struct {
	Payload *models.ExampleV1RfidDto
}

func (o *KeyServiceAddKeyOK) Error() string {
	return fmt.Sprintf("[POST /v1/keys][%d] keyServiceAddKeyOK  %+v", 200, o.Payload)
}

func (o *KeyServiceAddKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExampleV1RfidDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKeyServiceAddKeyDefault creates a KeyServiceAddKeyDefault with default headers values
func NewKeyServiceAddKeyDefault(code int) *KeyServiceAddKeyDefault {
	return &KeyServiceAddKeyDefault{
		_statusCode: code,
	}
}

/*KeyServiceAddKeyDefault handles this case with default header values.

An unexpected error response.
*/
type KeyServiceAddKeyDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the key service add key default response
func (o *KeyServiceAddKeyDefault) Code() int {
	return o._statusCode
}

func (o *KeyServiceAddKeyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/keys][%d] KeyService_AddKey default  %+v", o._statusCode, o.Payload)
}

func (o *KeyServiceAddKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
