package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"../../client/models"
)

// KeyServiceGetKeyReader is a Reader for the KeyServiceGetKey structure.
type KeyServiceGetKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KeyServiceGetKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewKeyServiceGetKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewKeyServiceGetKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKeyServiceGetKeyOK creates a KeyServiceGetKeyOK with default headers values
func NewKeyServiceGetKeyOK() *KeyServiceGetKeyOK {
	return &KeyServiceGetKeyOK{}
}

/*KeyServiceGetKeyOK handles this case with default header values.

A successful response.
*/
type KeyServiceGetKeyOK struct {
	Payload *models.ExampleV1RfidDto
}

func (o *KeyServiceGetKeyOK) Error() string {
	return fmt.Sprintf("[GET /v1/keys/{id}][%d] keyServiceGetKeyOK  %+v", 200, o.Payload)
}

func (o *KeyServiceGetKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExampleV1RfidDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKeyServiceGetKeyDefault creates a KeyServiceGetKeyDefault with default headers values
func NewKeyServiceGetKeyDefault(code int) *KeyServiceGetKeyDefault {
	return &KeyServiceGetKeyDefault{
		_statusCode: code,
	}
}

/*KeyServiceGetKeyDefault handles this case with default header values.

An unexpected error response.
*/
type KeyServiceGetKeyDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the key service get key default response
func (o *KeyServiceGetKeyDefault) Code() int {
	return o._statusCode
}

func (o *KeyServiceGetKeyDefault) Error() string {
	return fmt.Sprintf("[GET /v1/keys/{id}][%d] KeyService_GetKey default  %+v", o._statusCode, o.Payload)
}

func (o *KeyServiceGetKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
