package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyServiceGetKeyParams creates a new KeyServiceGetKeyParams object
// with the default values initialized.
func NewKeyServiceGetKeyParams() *KeyServiceGetKeyParams {
	var ()
	return &KeyServiceGetKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyServiceGetKeyParamsWithTimeout creates a new KeyServiceGetKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyServiceGetKeyParamsWithTimeout(timeout time.Duration) *KeyServiceGetKeyParams {
	var ()
	return &KeyServiceGetKeyParams{

		timeout: timeout,
	}
}

// NewKeyServiceGetKeyParamsWithContext creates a new KeyServiceGetKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyServiceGetKeyParamsWithContext(ctx context.Context) *KeyServiceGetKeyParams {
	var ()
	return &KeyServiceGetKeyParams{

		Context: ctx,
	}
}

// NewKeyServiceGetKeyParamsWithHTTPClient creates a new KeyServiceGetKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyServiceGetKeyParamsWithHTTPClient(client *http.Client) *KeyServiceGetKeyParams {
	var ()
	return &KeyServiceGetKeyParams{
		HTTPClient: client,
	}
}

/*KeyServiceGetKeyParams contains all the parameters to send to the API endpoint
for the key service get key operation typically these are written to a http.Request
*/
type KeyServiceGetKeyParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key service get key params
func (o *KeyServiceGetKeyParams) WithTimeout(timeout time.Duration) *KeyServiceGetKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key service get key params
func (o *KeyServiceGetKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key service get key params
func (o *KeyServiceGetKeyParams) WithContext(ctx context.Context) *KeyServiceGetKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key service get key params
func (o *KeyServiceGetKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key service get key params
func (o *KeyServiceGetKeyParams) WithHTTPClient(client *http.Client) *KeyServiceGetKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key service get key params
func (o *KeyServiceGetKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the key service get key params
func (o *KeyServiceGetKeyParams) WithID(id int32) *KeyServiceGetKeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the key service get key params
func (o *KeyServiceGetKeyParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *KeyServiceGetKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
