package key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"../../client/models"
)

// NewKeyServiceAddKeyParams creates a new KeyServiceAddKeyParams object
// with the default values initialized.
func NewKeyServiceAddKeyParams() *KeyServiceAddKeyParams {
	var ()
	return &KeyServiceAddKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyServiceAddKeyParamsWithTimeout creates a new KeyServiceAddKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyServiceAddKeyParamsWithTimeout(timeout time.Duration) *KeyServiceAddKeyParams {
	var ()
	return &KeyServiceAddKeyParams{

		timeout: timeout,
	}
}

// NewKeyServiceAddKeyParamsWithContext creates a new KeyServiceAddKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyServiceAddKeyParamsWithContext(ctx context.Context) *KeyServiceAddKeyParams {
	var ()
	return &KeyServiceAddKeyParams{

		Context: ctx,
	}
}

// NewKeyServiceAddKeyParamsWithHTTPClient creates a new KeyServiceAddKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyServiceAddKeyParamsWithHTTPClient(client *http.Client) *KeyServiceAddKeyParams {
	var ()
	return &KeyServiceAddKeyParams{
		HTTPClient: client,
	}
}

/*KeyServiceAddKeyParams contains all the parameters to send to the API endpoint
for the key service add key operation typically these are written to a http.Request
*/
type KeyServiceAddKeyParams struct {

	/*Body
	  The key resource to create.

	*/
	Body *models.ExampleV1RfidDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key service add key params
func (o *KeyServiceAddKeyParams) WithTimeout(timeout time.Duration) *KeyServiceAddKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key service add key params
func (o *KeyServiceAddKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key service add key params
func (o *KeyServiceAddKeyParams) WithContext(ctx context.Context) *KeyServiceAddKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key service add key params
func (o *KeyServiceAddKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key service add key params
func (o *KeyServiceAddKeyParams) WithHTTPClient(client *http.Client) *KeyServiceAddKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key service add key params
func (o *KeyServiceAddKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the key service add key params
func (o *KeyServiceAddKeyParams) WithBody(body *models.ExampleV1RfidDto) *KeyServiceAddKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the key service add key params
func (o *KeyServiceAddKeyParams) SetBody(body *models.ExampleV1RfidDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *KeyServiceAddKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.ExampleV1RfidDto)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
